#!/bin/bash
git pull
cp -rf ~/github/lamp/* ~/webapps/lamp/
cd ~/webapps/lamp/
npm install
source .env
pm2 start $PWD/app.coffee --name lamp -e /home/wileycousins/.pm2/logs/lamp-err.log -o /home/wileycousins/pm2/logs/lamp-out.log
